### PR TITLE
Set input sizes to match batchsize

### PR DESCRIPTION
**Pull request by davidbau**
Also, fix indexing errors with ragged batches (verifying that ragged inputs with shorter-than-specified batches still produce ragged outputs with matching sizes).

### CODE REVIEW

**Comment by davidbau** [comment]
Note that we could pad the last batch - the code would look like this: https://github.com/jonhoo/periscope/compare/pad-last-batch - but I think the branch in this pull request is cleaner.

**Comment by jonhoo** [comment]
Most of the changes in that commit (i.e., all the `batch` => `inp, res` changes) are unrelated to the actual change. Can you split this into two commits for clarity?

From what I can tell, the only semantic changes made by this commit are

``` diff
@@ -84,7 +84,7 @@
 prepared = cropped[:,:,:,::flip_var]

 # create a small convolutional neural network
-network = lasagne.layers.InputLayer((None, 3, cropsz, cropsz), prepared)
+network = lasagne.layers.InputLayer((args.batchsize, 3, cropsz, cropsz), prepared)
 # 1st
 network = Conv2DLayer(network, 64, (8, 8), stride=2, nonlinearity=rectify)
 network = BatchNormLayer(network, nonlinearity=rectify)
@@ -391,7 +391,7 @@ def latest_cachefile(outdir):
         pred_out[s:s+args.batchsize, :] = debug_fn(1, center, batch[0])
         i += 1
         p.update(i)
         topindex = numpy.argsort(-pred_out[s:s+args.batchsize], axis=1)
-        for index in range(args.batchsize):
+        for index in range(topindex.shape[0]):
             confusion = numpy.where(topindex[index] == batch[1][index])[0][0]
             accn[confusion] = accn.get(confusion, 0) + 1
         correct = 0
     for index in range(10):
```

**Comment by davidbau** [comment]
OK, split into two separate commits for clarity.

Oops, hold on, messed up the patch.  Rebasing again.

**Comment by davidbau** [comment]
OK, fixed the commits.

**Comment by jonhoo** [comment]
Looks good!

**Pull request merged**
